Moved over deletion methods from the mobile version of the library
uport-project/UPTEthereumSigner pull request #25
Opened 2018-11-17 18:21 UTC by pelle

Note I am uncertain how to run tests, so please run tests before merging in.

2018-11-17 20:26 UTC, wjmelements commented
Can you link the mobile version referenced in the title?

2018-11-17 20:28 UTC, wjmelements requested changes

2018-11-17 20:28 UTC, wjmelements commented on UPTEthereumSignerTests/UPTHDSignerSpec.m
> +                                     XCTAssertNil(error);
This test should also verify that the seed was deleted.

2018-11-17 21:31 UTC, wjmelements commented
@pelle To run the tests, open the workspace in XCode and run Test on the UPTEthereumSigner target.

I have ran the tests on this branch; they pass.

2018-11-17 21:33 UTC, wjmelements commented
Here is a doc from Apple on how to run tests in XCode https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/05-running_tests.html

2018-11-18 18:43 UTC, pelle commented
@wjmelements This is the local changes made in the app version of this code https://github.com/uport-project/uport-mobile/tree/develop/ios/uPortMobile

The test option is greyed out in my xcode. It may be because I'm on XCode 10.1.

2018-11-22 18:53 UTC, meaning-matters approved these changes
All tests run (I do see failed assertions (as I did on develop branch a few days ago), so assume that's normal; will keep that in mind check in coming weeks).

2018-11-22 18:59 UTC, pelle commented
They all pass for me now @meaning-matters

2018-11-22 21:45 UTC, merged