Replace with Carthage based setup and eliminate Specta from tests
uport-project/UPTEthereumSigner pull request #29
Opened 2019-01-30 15:51 UTC by meaning-matters

This reorganizes files, and replaces CocoaPods with Carthage.

Under CocoaPods all cloned pods sources were part of this repo; for Carthage I've chosen, as discussed, to not include cloned repos. But Carthage has the same option, so if we think it's better to include everything, we can easily do that.

I had to rename the `UPTEthereumSigner` class to `UPTEthSigner` because the `UPTEthereumSigner.h` must be used as framework API/header.

Specta, an old Obj-C testing package has been eliminated; iOS' own testing framework is sufficient and the code looks much better without Specta. There are of lot of tests failing; I guess it's because these tests are outdated, but I still need to check if that's 'correct'.

I've also reformatted the existing code (quite some lines were very long, had inconsistent spacing, had unclear indentation, ...).  Looks much better now and in line with recently added JWT verification, DID resolving, and Sodium encryption work.  (I thought it was a good time for that because no logic code changes/additions were made; but I could undo that for now and place it in a separate PR.)

2019-01-30 15:54 UTC, meaning-matters commented
Xcode project and config files may still change a bit. Changes might be needed when trying to use this framework in the uPort SDK.

2019-01-30 15:56 UTC, meaning-matters commented
Tests only run on the simulator at the moment. A test app needs to be added to allow them to run on a device; I want to add that consistently to all new Carthage/framework-based repos later.

2019-01-31 15:30 UTC, mirceanis requested changes
I'm really glad so much code has been removed from this repo.
The `UPTEthereumSigner`->`UPTEthSigner` rename seems like an unnecessary breaking change so I'm requesting that be undone.
Otherwise nice work, thanks!

2019-01-31 15:30 UTC, mirceanis commented on UPTEthereumSigner/UPTEthSigner.h
> +@interface UPTEthSigner : NSObject
The `UPTEthereumSigner` class is part of the main API of this library and renaming it seems like an unnecessary breaking change that will force downstream developers to refactor.
Is there a reason for renaming it that I'm not aware of?

2021-02-04 17:15 UTC, closed without merging

2021-02-04 17:16 UTC, meaning-matters commented
Done